version: "3"
services:
  landing:
    container_name: dimosio-landing
    restart: unless-stopped
    image: nginx
    networks:
     - nginx-proxy
    volumes:
    # Mount this code into /code
      - ./:/usr/share/nginx/html:ro
    environment:
      NGINX_PORT: ${LANDING_VPORT}
      VIRTUAL_HOST: ${LANDING_VHOST}
      VIRTUAL_PORT: ${LANDING_VPORT}
      LETSENCRYPT_HOST: ${LANDING_VHOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
    expose:
      - ${LANDING_VPORT}

networks:
  nginx-proxy:
    external:
      name: proxy_default